### ISSUE TITLE
The performance is lower than reported ?

### ISSUE THREAD

**Issue by SunGuoYing** [qjadud1994/DRS#3]
Amazing Work! When I used the provided code and followed the method in your paper, I only got val 69.45 with learnable DRS. How can I get the same performance as reported in your paper？

**Comment by qjadud1994** [comment]
Did your performance include the DenseCRF post-processing?

Since the seed is not fixed, there may be a gap of about 1% performance.

We think higher performance can be obtained if a different seed is used, or if calculating the best validation score during the DeepLab-V2 training.

**Comment by SunGuoYing** [comment]
Thank you for your early reply! I still have two questions and I am looking forward to your answers:
1、Have you ever tried to use DRS module on ResNet50? I replaced all the Relu on ResNet50 with DRS module, but the result was not good. Do you have any suggestions for using it.
2、Why do you add extra layers of convolution after VGG16? Do I need to add these extra convolutional layers when I use it on resnet50?
Thank you very much!
