### ISSUE TITLE
Model in ResNet50

### ISSUE THREAD

**Issue by Ferenas** [qjadud1994/DRS#6]
Hi, thanks for your great work! I was wondering if DRS could be adapted in RESNET50. Have you ever tried it on ResNet? I have tried DRS in some layers buy found limited improvement. Do you have any suggestion?

**Comment by qjadud1994** [comment]
We think the 'BatchNorm' or 'skip connection' is the matter for the ResNet. 
The location of the DRS module plays an important role.
For example, Conv-BN-DRS or Conv-DRS-BN, DRS before or after skip-connection.
We remain that as our future work.

**Comment by Ferenas** [comment]
Thanks for your quick response! I will also tri it. Besides, Why don't you use Affinity Net to improve the CAMs quality as most WSSS methods do? Is this because such DRS module will lead to a limited performance in calculating Affinity since CAM has been intensified?

**Comment by qjadud1994** [comment]
When we did our paperwork, we thought that affinitynet-refinement is one of the off-the-shelf techniques that boosts the performance like DenseCRF; that cannot be our contributions.

Our method takes the advantage of saliency information, so we guess the effect of affinity-refinement might be marginal.
However, It's worth a try.
