### ISSUE TITLE
It's too slow to download the saliency_map from google cloud in China.

### ISSUE THREAD

**Issue by KKIverson** [qjadud1994/DRS#9]
Can you just share the saliency_map in the way of zip file, and not using the goole cloud? 

I'm crying downloading this.

**Comment by qjadud1994** [comment]
ok then, Onedrive or Dropbox is available?

Otherwise, could you suggest an alternative way?

**Comment by KKIverson** [comment]
Thank you， I‘ve downloaded the saliency_maps from your link. It might be the newwork reason.
